#!/bin/bash

# You must create a symlink to make this hook work:
#     cd .git/hooks
#     ln -s ../../git_hooks/pre-commit

file="CubicDone/Network/APIConstants.swift"

regex="vkApiToken.*=.*\"(.*)\"$"

while IFS= read -r line; do
    if [[ $line =~ $regex ]]; then
        modified_line="${line//${BASH_REMATCH[1]}/<token>}"
        echo "$modified_line"
    else
        echo "$line"
    fi
done < "$file" > temp

mv temp "$file"
